export const SESSION_DURATION_MINUTES_MIN = 30;
export const SESSION_DURATION_MINUTES_MAX = 180;
export const SESSION_DURATION_MINUTES_STEP = 5;
export const SESSION_DURATION_MINUTES_DEFAULT = 90;

export const SESSION_PARTICIPANTS_MIN = 1;
export const SESSION_PARTICIPANTS_MAX = 10;
export const SESSION_PARTICIPANTS_DEFAULT = 5;
