import { getServerAuthState } from "@/lib/auth/server";
import { AuthStoreProvider } from "@/providers/AuthStoreProvider";
import { QueryProvider } from "@/providers/QueryProvider";
import type { Metadata } from "next";
import { geistMono, geistSans, pretendard } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 서버에서 쿠키를 읽어 초기 인증 상태 확인
  const initialAuth = await getServerAuthState();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pretendard.variable} font-sans antialiased`}
      >
        <AuthStoreProvider initialAuth={initialAuth}>
          <QueryProvider>{children}</QueryProvider>
        </AuthStoreProvider>
      </body>
    </html>
  );
}
