import {
  ALPHA_BLACK_COLORS,
  ALPHA_WHITE_COLORS,
  BORDER_SAMPLES,
  BORDER_WIDTH_SAMPLES,
  COMMON_COLORS,
  CYAN_SCALE,
  DIVIDER_SAMPLES,
  GAP_SAMPLES,
  GRAY_SCALE,
  GREEN_SCALE,
  OVERLAY_COLORS,
  RADIUS_SAMPLES,
  RED_SCALE,
  SEMANTIC_BACKGROUNDS,
  SEMANTIC_SURFACES,
  SPACING_SAMPLES,
  TEAL_SCALE,
  TEXT_COLORS,
  TYPOGRAPHY_SAMPLES,
  YELLOW_SCALE,
} from "./tokensData";
import {
  BorderSection,
  BorderWidthSection,
  ColorSection,
  DividerSection,
  GapSection,
  RadiusSection,
  SectionGroup,
  SpacingSection,
  TextColorSection,
  TypographySection,
} from "./TokenSections";

export default function TokensTestPage() {
  const borderWidthLabels = BORDER_WIDTH_SAMPLES.map((item) => item.label).join(", ");

  return (
    <div className="bg-background-default min-h-screen text-gray-900">
      <div className="gap-2xl p-2xl mx-auto flex max-w-7xl flex-col">
        <header className="gap-sm flex flex-col">
          <h1 className="text-3xl font-semibold">Design Tokens Test</h1>
          <p className="text-gray-600">
            Comprehensive test page for all design tokens generated by Style Dictionary for Tailwind
            v4.
          </p>
        </header>

        <SectionGroup title="Semantic Colors">
          <ColorSection title="Background Colors" items={SEMANTIC_BACKGROUNDS} columns={4} />
          <ColorSection title="Surface Colors" items={SEMANTIC_SURFACES} columns={5} />
        </SectionGroup>

        <SectionGroup title="Border & Divider Colors">
          <BorderSection title="Border Colors" items={BORDER_SAMPLES} />
          <DividerSection title="Divider Colors" items={DIVIDER_SAMPLES} />
        </SectionGroup>

        <SectionGroup title="Primitive Colors">
          <ColorSection title="Gray Scale" items={GRAY_SCALE} columns={11} />
          <ColorSection title="Green Scale (Primary)" items={GREEN_SCALE} columns={11} />
          <ColorSection title="Teal Scale (Secondary)" items={TEAL_SCALE} columns={11} />
          <ColorSection title="Red Scale (Error)" items={RED_SCALE} columns={11} />
          <ColorSection title="Yellow Scale (Warning)" items={YELLOW_SCALE} columns={11} />
          <ColorSection title="Cyan Scale (Success)" items={CYAN_SCALE} columns={11} />
          <ColorSection title="Common Colors" items={COMMON_COLORS} columns={4} />
        </SectionGroup>

        <SectionGroup title="Alpha Colors">
          <ColorSection title="Alpha Black" items={ALPHA_BLACK_COLORS} columns={6} />
          <ColorSection title="Alpha White" items={ALPHA_WHITE_COLORS} columns={6} />
        </SectionGroup>

        <SectionGroup title="Overlay Colors">
          <ColorSection title="Overlay" items={OVERLAY_COLORS} columns={3} />
        </SectionGroup>

        <SectionGroup title="Text Colors">
          <TextColorSection title="Text Colors" items={TEXT_COLORS} />
        </SectionGroup>

        <SectionGroup title="Spacing & Layout">
          <SpacingSection title="Spacing Scale (padding)" items={SPACING_SAMPLES} />
          <GapSection title="Gap Scale" items={GAP_SAMPLES} />
        </SectionGroup>

        <SectionGroup title="Shape (Radius & Border Width)">
          <RadiusSection title="Border Radius" items={RADIUS_SAMPLES} />
          <BorderWidthSection title="Border Width" items={BORDER_WIDTH_SAMPLES} />
        </SectionGroup>

        <SectionGroup title="Typography">
          <TypographySection title="Font Family & Weights" items={TYPOGRAPHY_SAMPLES} />
        </SectionGroup>

        <footer className="mt-xl border-border-gray-default pt-xl border-t">
          <div className="bg-surface-subtle p-lg rounded-lg">
            <h3 className="mb-sm text-lg font-semibold">Token Summary</h3>
            <ul className="gap-sm grid grid-cols-2 text-sm md:grid-cols-4">
              <li>
                <strong>Semantic Colors:</strong> Background, Surface
              </li>
              <li>
                <strong>Border/Divider:</strong> {BORDER_SAMPLES.length} borders,{" "}
                {DIVIDER_SAMPLES.length} dividers
              </li>
              <li>
                <strong>Primitive Colors:</strong> Gray, Green, Teal, Red, Yellow, Cyan
              </li>
              <li>
                <strong>Alpha Colors:</strong> Black, White opacity variants
              </li>
              <li>
                <strong>Spacing:</strong> none ~ 4xl ({SPACING_SAMPLES.length} values)
              </li>
              <li>
                <strong>Gap:</strong> none ~ 3xl ({GAP_SAMPLES.length} values)
              </li>
              <li>
                <strong>Radius:</strong> none ~ max ({RADIUS_SAMPLES.length} values)
              </li>
              <li>
                <strong>Border Width:</strong> {borderWidthLabels}
              </li>
            </ul>
          </div>
        </footer>
      </div>
    </div>
  );
}
