import {
  BorderSection,
  BorderWidthSection,
  ColorSection,
  DividerSection,
  GapSection,
  RadiusSection,
  SectionGroup,
  SpacingSection,
  TypographySection,
} from "./TokenSections";
import {
  BLACK_OPACITY_COLORS,
  BORDER_SAMPLES,
  BORDER_WIDTH_SAMPLES,
  COMMON_COLORS,
  DIVIDER_SAMPLES,
  ERROR_SCALE,
  GAP_SAMPLES,
  GRAY_OPACITY_COLORS,
  GRAY_SCALE,
  LIGHT_ERROR_SCALE,
  LIGHT_GRAY_SCALE,
  LIGHT_POINT_SCALE,
  LIGHT_PRIMARY_SCALE,
  LIGHT_SECONDARY_SCALE,
  LIGHT_SUCCESS_SCALE,
  LIGHT_WARNING_SCALE,
  POINT_SCALE,
  PRIMARY_SCALE,
  RADIUS_SAMPLES,
  SECONDARY_SCALE,
  SEMANTIC_BACKGROUNDS,
  SEMANTIC_SURFACES,
  SPACING_SAMPLES,
  SUCCESS_SCALE,
  TYPOGRAPHY_SAMPLES,
  WARNING_SCALE,
  WHITE_OPACITY_COLORS,
  WHITE_OPACITY_COLORS_2,
} from "./tokensData";

export default function TokensTestPage() {
  const borderWidthLabels = BORDER_WIDTH_SAMPLES.map((item) => item.label).join(", ");

  return (
    <div className="bg-background-white text-light-gray-90 min-h-screen">
      <div className="gap-2xl p-2xl mx-auto flex max-w-7xl flex-col">
        <header className="gap-sm flex flex-col">
          <h1 className="text-3xl font-semibold">Design Tokens Test</h1>
          <p className="text-light-gray-60">
            Comprehensive test page for all design tokens generated by Style Dictionary for Tailwind
            v4.
          </p>
        </header>

        <SectionGroup title="Semantic Colors">
          <ColorSection title="Background Colors" items={SEMANTIC_BACKGROUNDS} columns={5} />
          <ColorSection title="Surface Colors" items={SEMANTIC_SURFACES} columns={6} />
        </SectionGroup>

        <SectionGroup title="Border & Divider Colors">
          <BorderSection title="Border Colors" items={BORDER_SAMPLES} />
          <DividerSection title="Divider Colors" items={DIVIDER_SAMPLES} />
        </SectionGroup>

        <SectionGroup title="Primitive Colors (light.*)">
          <ColorSection title="Light Gray Scale" items={LIGHT_GRAY_SCALE} columns={6} />
          <ColorSection title="Light Primary Scale" items={LIGHT_PRIMARY_SCALE} columns={11} />
          <ColorSection title="Light Secondary Scale" items={LIGHT_SECONDARY_SCALE} columns={11} />
          <ColorSection title="Light Point Scale" items={LIGHT_POINT_SCALE} columns={4} />
          <ColorSection title="Light Error Scale" items={LIGHT_ERROR_SCALE} columns={11} />
          <ColorSection title="Light Warning Scale" items={LIGHT_WARNING_SCALE} columns={11} />
          <ColorSection title="Light Success Scale" items={LIGHT_SUCCESS_SCALE} columns={11} />
          <ColorSection title="Common Colors" items={COMMON_COLORS} columns={4} />
        </SectionGroup>

        <SectionGroup title="Opacity Colors">
          <ColorSection title="Light Gray Opacity" items={GRAY_OPACITY_COLORS} columns={6} />
          <ColorSection
            title="Light White Opacity (dark bg)"
            items={WHITE_OPACITY_COLORS}
            columns={6}
          />
          <ColorSection title="Black Opacity" items={BLACK_OPACITY_COLORS} columns={6} />
          <ColorSection
            title="White Opacity (dark bg)"
            items={WHITE_OPACITY_COLORS_2}
            columns={6}
          />
        </SectionGroup>

        <SectionGroup title="Alias Colors">
          <ColorSection title="Gray Scale" items={GRAY_SCALE} columns={11} />
          <ColorSection title="Primary Scale" items={PRIMARY_SCALE} columns={11} />
          <ColorSection title="Secondary Scale" items={SECONDARY_SCALE} columns={11} />
          <ColorSection title="Point Scale" items={POINT_SCALE} columns={3} />
          <ColorSection title="Error Scale" items={ERROR_SCALE} columns={11} />
          <ColorSection title="Warning Scale" items={WARNING_SCALE} columns={11} />
          <ColorSection title="Success Scale" items={SUCCESS_SCALE} columns={11} />
        </SectionGroup>

        <SectionGroup title="Spacing & Layout">
          <SpacingSection title="Spacing Scale (padding)" items={SPACING_SAMPLES} />
          <GapSection title="Gap Scale" items={GAP_SAMPLES} />
        </SectionGroup>

        <SectionGroup title="Shape (Radius & Border Width)">
          <RadiusSection title="Border Radius" items={RADIUS_SAMPLES} />
          <BorderWidthSection title="Border Width" items={BORDER_WIDTH_SAMPLES} />
        </SectionGroup>

        <SectionGroup title="Typography">
          <TypographySection title="Font Family & Weights" items={TYPOGRAPHY_SAMPLES} />
        </SectionGroup>

        <footer className="mt-xl border-border-gray-light pt-xl border-t">
          <div className="bg-surface-gray-subtle p-lg rounded-lg">
            <h3 className="mb-sm text-lg font-semibold">Token Summary</h3>
            <ul className="gap-sm grid grid-cols-2 text-sm md:grid-cols-4">
              <li>
                <strong>Semantic Colors:</strong> Background, Surface
              </li>
              <li>
                <strong>Border/Divider:</strong> {BORDER_SAMPLES.length} borders,{" "}
                {DIVIDER_SAMPLES.length} dividers
              </li>
              <li>
                <strong>Primitive Colors:</strong> Gray, Primary, Secondary, Point, Error, Warning,
                Success
              </li>
              <li>
                <strong>Opacity Colors:</strong> Gray, White, Black opacity variants
              </li>
              <li>
                <strong>Spacing:</strong> none ~ 4xl ({SPACING_SAMPLES.length} values)
              </li>
              <li>
                <strong>Gap:</strong> none ~ 3xl ({GAP_SAMPLES.length} values)
              </li>
              <li>
                <strong>Radius:</strong> none ~ max ({RADIUS_SAMPLES.length} values)
              </li>
              <li>
                <strong>Border Width:</strong> {borderWidthLabels}
              </li>
            </ul>
          </div>
        </footer>
      </div>
    </div>
  );
}
