import {
  BorderSection,
  BorderWidthSection,
  ColorSection,
  DividerSection,
  GapSection,
  RadiusSection,
  SectionGroup,
  SpacingSection,
  TypographySection,
} from "./TokenSections";
import {
  blackOpacityColors,
  borderSamples,
  borderWidthSamples,
  commonColors,
  dividerSamples,
  errorScale,
  gapSamples,
  grayOpacityColors,
  grayScale,
  lightErrorScale,
  lightGrayScale,
  lightPointScale,
  lightPrimaryScale,
  lightSecondaryScale,
  lightSuccessScale,
  lightWarningScale,
  pointScale,
  primaryScale,
  radiusSamples,
  secondaryScale,
  semanticBackgrounds,
  semanticSurfaces,
  spacingSamples,
  successScale,
  typographySamples,
  warningScale,
  whiteOpacityColors,
  whiteOpacityColors2,
} from "./tokensData";

export default function TokensTestPage() {
  const borderWidthLabels = borderWidthSamples.map((item) => item.label).join(", ");

  return (
    <div className="bg-background-white text-light-gray-90 min-h-screen">
      <div className="gap-2xl p-2xl mx-auto flex max-w-7xl flex-col">
        <header className="gap-sm flex flex-col">
          <h1 className="text-3xl font-semibold">Design Tokens Test</h1>
          <p className="text-light-gray-60">
            Comprehensive test page for all design tokens generated by Style Dictionary for Tailwind
            v4.
          </p>
        </header>

        <SectionGroup title="Semantic Colors">
          <ColorSection title="Background Colors" items={semanticBackgrounds} columns={5} />
          <ColorSection title="Surface Colors" items={semanticSurfaces} columns={6} />
        </SectionGroup>

        <SectionGroup title="Border & Divider Colors">
          <BorderSection title="Border Colors" items={borderSamples} />
          <DividerSection title="Divider Colors" items={dividerSamples} />
        </SectionGroup>

        <SectionGroup title="Primitive Colors (light.*)">
          <ColorSection title="Light Gray Scale" items={lightGrayScale} columns={6} />
          <ColorSection title="Light Primary Scale" items={lightPrimaryScale} columns={11} />
          <ColorSection title="Light Secondary Scale" items={lightSecondaryScale} columns={11} />
          <ColorSection title="Light Point Scale" items={lightPointScale} columns={4} />
          <ColorSection title="Light Error Scale" items={lightErrorScale} columns={11} />
          <ColorSection title="Light Warning Scale" items={lightWarningScale} columns={11} />
          <ColorSection title="Light Success Scale" items={lightSuccessScale} columns={11} />
          <ColorSection title="Common Colors" items={commonColors} columns={4} />
        </SectionGroup>

        <SectionGroup title="Opacity Colors">
          <ColorSection title="Light Gray Opacity" items={grayOpacityColors} columns={6} />
          <ColorSection
            title="Light White Opacity (dark bg)"
            items={whiteOpacityColors}
            columns={6}
          />
          <ColorSection title="Black Opacity" items={blackOpacityColors} columns={6} />
          <ColorSection title="White Opacity (dark bg)" items={whiteOpacityColors2} columns={6} />
        </SectionGroup>

        <SectionGroup title="Alias Colors">
          <ColorSection title="Gray Scale" items={grayScale} columns={11} />
          <ColorSection title="Primary Scale" items={primaryScale} columns={11} />
          <ColorSection title="Secondary Scale" items={secondaryScale} columns={11} />
          <ColorSection title="Point Scale" items={pointScale} columns={3} />
          <ColorSection title="Error Scale" items={errorScale} columns={11} />
          <ColorSection title="Warning Scale" items={warningScale} columns={11} />
          <ColorSection title="Success Scale" items={successScale} columns={11} />
        </SectionGroup>

        <SectionGroup title="Spacing & Layout">
          <SpacingSection title="Spacing Scale (padding)" items={spacingSamples} />
          <GapSection title="Gap Scale" items={gapSamples} />
        </SectionGroup>

        <SectionGroup title="Shape (Radius & Border Width)">
          <RadiusSection title="Border Radius" items={radiusSamples} />
          <BorderWidthSection title="Border Width" items={borderWidthSamples} />
        </SectionGroup>

        <SectionGroup title="Typography">
          <TypographySection title="Font Family & Weights" items={typographySamples} />
        </SectionGroup>

        <footer className="mt-xl border-border-gray-light pt-xl border-t">
          <div className="bg-surface-gray-subtle p-lg rounded-lg">
            <h3 className="mb-sm text-lg font-semibold">Token Summary</h3>
            <ul className="gap-sm grid grid-cols-2 text-sm md:grid-cols-4">
              <li>
                <strong>Semantic Colors:</strong> Background, Surface
              </li>
              <li>
                <strong>Border/Divider:</strong> {borderSamples.length} borders,{" "}
                {dividerSamples.length} dividers
              </li>
              <li>
                <strong>Primitive Colors:</strong> Gray, Primary, Secondary, Point, Error, Warning,
                Success
              </li>
              <li>
                <strong>Opacity Colors:</strong> Gray, White, Black opacity variants
              </li>
              <li>
                <strong>Spacing:</strong> none ~ 4xl ({spacingSamples.length} values)
              </li>
              <li>
                <strong>Gap:</strong> none ~ 3xl ({gapSamples.length} values)
              </li>
              <li>
                <strong>Radius:</strong> none ~ max ({radiusSamples.length} values)
              </li>
              <li>
                <strong>Border Width:</strong> {borderWidthLabels}
              </li>
            </ul>
          </div>
        </footer>
      </div>
    </div>
  );
}
