/**
 * Tailwind v4 @theme Format
 * tokens-studio/sd-tailwindv4 레포지토리 패턴 기반
 *
 * 역할:
 * - Style Dictionary 토큰을 Tailwind v4의 `@theme inline` 블록으로 변환
 * - Figma/Token Studio 토큰 구조(path)를 기반으로 카테고리 분류
 * - Tailwind v4 호환 네이밍으로 변환하고 CSS 변수 선언을 생성
 * - 참조 토큰은 CSS 변수(var(--...))로 치환하고 길이 값은 px 단위로 보정
 *
 * 입력: dictionary.allTokens (Style Dictionary 토큰 목록)
 * 출력: @theme inline { --token-name: value; } 형태의 CSS 문자열
 */

import { convertTokenReference, withPx } from "../helpers/unit-converter.mjs";

/**
 * 토큰 카테고리 분류
 */
function categorizeToken(token) {
  const category = token.path[0];
  const isSpacing = category === "layout" && token.path[1] === "spacing";
  const isGap = category === "layout" && token.path[1] === "gap";
  const isRadius = category === "shape" && token.path[1] === "radius";
  const isBorderWidth = category === "shape" && token.path[1] === "border-width";

  return {
    category,
    isSpacing,
    isGap,
    isRadius,
    isBorderWidth,
    needsLengthUnit: isSpacing || isGap || isRadius || isBorderWidth,
  };
}

/**
 * Tailwind v4 호환 네이밍으로 변환
 */
function convertTokenName(tokenName) {
  const nameMapping = {
    "layout-spacing-": "spacing-",
    "layout-gap-": "gap-",
    "shape-radius-": "radius-",
    "shape-border-width-": "border-width-",
    "typo-family-": "font-",
    "typo-weight-": "font-weight-",
  };

  for (const [prefix, replacement] of Object.entries(nameMapping)) {
    if (tokenName.startsWith(prefix)) {
      return tokenName.replace(prefix, replacement);
    }
  }

  return tokenName;
}

/**
 * 토큰 값 처리 (참조 변환 및 단위 추가)
 */
function processTokenValue(token, outputReferences, needsLengthUnit) {
  let value = token.value;

  // outputReferences 처리 - 토큰 값이 다른 토큰을 참조하는지 확인
  if (outputReferences && token.original?.value) {
    const refValue = convertTokenReference(token.original.value);
    if (refValue) value = refValue;
  }

  // 길이 단위가 필요한 경우 px 추가
  if (needsLengthUnit) {
    value = withPx(value);
  }

  return value;
}

/**
 * CSS 변수 생성
 */
function createCssVariable(tokenName, value) {
  return `  --${tokenName}: ${value};`;
}

/**
 * 카테고리별 섹션 생성
 */
function generateSections(tokensByCategory) {
  const sectionConfig = [
    {
      key: "colors",
      comment: "Colors - Tailwind이 자동으로 bg-, text-, border- 유틸리티 생성",
    },
    { key: "spacing", comment: "Spacing - p-, m- 유틸리티 생성" },
    { key: "gap", comment: "Gap - gap- 유틸리티 생성" },
    { key: "radius", comment: "Border Radius - rounded- 유틸리티 생성" },
    { key: "borderWidth", comment: "Border Width - border- 유틸리티 생성" },
    { key: "typography", comment: "Typography" },
    { key: "other", comment: "Other" },
  ];

  return sectionConfig
    .filter(({ key }) => tokensByCategory[key].length > 0)
    .map(({ key, comment }) => `  /* ${comment} */\n${tokensByCategory[key].join("\n")}`);
}

/**
 * Tailwind v4 @theme 포맷
 */
export const tailwindV4Format = {
  name: "css/tailwind-theme",
  format({ dictionary, options = {} }) {
    const { outputReferences = true } = options;

    // 토큰을 카테고리별로 그룹화
    const tokensByCategory = {
      colors: [],
      spacing: [],
      gap: [],
      radius: [],
      borderWidth: [],
      typography: [],
      other: [],
    };

    dictionary.allTokens.forEach((token) => {
      const { category, isSpacing, isGap, isRadius, isBorderWidth, needsLengthUnit } =
        categorizeToken(token);

      // 토큰 값 처리
      const value = processTokenValue(token, outputReferences, needsLengthUnit);

      // 토큰 네이밍 변환
      const tokenName = convertTokenName(token.name);

      // CSS 변수 생성
      const cssVar = createCssVariable(tokenName, value);

      // 카테고리별로 분류
      if (category === "color") {
        tokensByCategory.colors.push(cssVar);
      } else if (isSpacing) {
        tokensByCategory.spacing.push(cssVar);
      } else if (isGap) {
        tokensByCategory.gap.push(cssVar);
      } else if (isRadius) {
        tokensByCategory.radius.push(cssVar);
      } else if (isBorderWidth) {
        tokensByCategory.borderWidth.push(cssVar);
      } else if (category === "typo") {
        tokensByCategory.typography.push(cssVar);
      } else {
        tokensByCategory.other.push(cssVar);
      }
    });

    // @theme 블록 생성
    const sections = generateSections(tokensByCategory);

    return `/**
 * Tailwind v4 Design Tokens
 * Auto-generated by Style Dictionary
 * DO NOT EDIT DIRECTLY
 */

@theme inline {
${sections.join("\n\n")}
}
`;
  },
};
